spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: posts-route
          uri: ${POSTS_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/posts/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service
        - id: comments-route
          uri: ${COMMENTS_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/comments/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

#
#spring:
#  main:
#    web-application-type: reactive
#  application:
#    name: gateway-tbj
#  cloud:
#    gateway:
#      routes:
#      - predicates:
#        - Path=/api/public/**
#        uri: ${http://localhost:52345}
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#    gateway:
#      enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: "http://127.0.0.1:8761/eureka/"
